export const provinciasList = [
  "Azuay",
  "Bolivar",
  "Cañar",
  "Carchi",
  "Chimborazo",
  "Cotopaxi",
  "El Oro",
  "Esmeraldas",
  "Galápagos",
  "Guayanas",
  "Imbabura",
  "Loja",
  "Los Ríos",
  "Manabí",
  "Morona Santiago",
  "Napo",
  "Sucumbíos",
  "Pastaza",
  "Pichincha",
  "Santa Elena",
  "Santo Domingo",
  "Francisco De Orellana",
  "Tungurahua",
  "Zamora Chinchipe",
]

export const materiasList = [
"Derecho Administrativo",
"Derecho Penal",
"Derecho Constitucional",
"Derecho Procesal",
"Derecho Ambiental",
"Derecho Laboral",
"Derecho Civil",
"Derecho de Familia",
"Derecho Tributario",
"Transito",
"Derecho Coorporativo",
"Derecho Sucesorio",
"Derecho Mercantil",
"Derecho Internacional Privado",
"Derecho Internacional Publico" 
]

export const abogadosList = [
  {
    id: 1,
    name: 'Victor Salazar',
    profileImage: 'https://i.pravatar.cc/309',
    description: '',
    email: 'xavicoel@gmail.com',
    phoneNumber: "593969044674",
    city: 'Quito',
    province: 'Pichincha',
    especialidad: ["Derecho Administrativo", "Derecho Penal"],
    rating: "3⭐"
  },
  {
    id: 2,
    name: 'Cristina Escobar',
    profileImage: 'https://i.pravatar.cc/308',
    description: '',
    email: 'criscobar01@gmail.com',
    city: 'Ambato',
    province: 'Tungurahua',
    phoneNumber: "59396923i283",
    especialidad: ["Derecho Internacional Publico", "Derecho Mercantil"],
    rating: "3⭐"
  },
  {
    id: 3,
    name: 'Gabriel Alvarado',
    profileImage: 'https://i.pravatar.cc/305',
    description: '',
    email: 'gabriel01@gmail.com',
    city: 'Carchi',
    province: 'Carchi',
    phoneNumber: "5939692234283",
    especialidad: ["Derecho de Familia", "Derecho Civil"],
    rating: "5⭐"
  },
  {
    id: 4,
    name: 'Nicolaz munoz',
    profileImage: 'https://i.pravatar.cc/301',
    description: '',
    email: 'gabriel01@gmail.com',
    city: 'Carchi',
    province: 'Carchi',
    phoneNumber: "5939692234283",
    especialidad: ["Derecho Civil", "Transito"],
    rating: "3⭐"
  },
  {
    id: 5,
    name: 'Pedro dominguez',
    profileImage: 'https://i.pravatar.cc/302',
    description: '',
    email: 'gabriel01@gmail.com',
    city: 'Carchi',
    province: 'Carchi',
    phoneNumber: "5939692234283",
    especialidad: ["Derecho Internacional Publico", "Derecho Sucesorio"],
    rating: "4⭐"
  },
  {
    id: 6,
    name: 'Marco jativa',
    profileImage: 'https://i.pravatar.cc/303',
    description: '',
    email: 'gabriel01@gmail.com',
    city: 'Carchi',
    province: 'Carchi',
    phoneNumber: "5939692234283",
    especialidad: ["Derecho Tributario", "Derecho Mercantil"],
    rating: "5⭐"
  },

]

export const categoryList = [
    {
      id: 1,
      value: 'place',
      label: '🚩 Places',
    },
    {
      id: 2,
      value: 'dish',
      label: '🍕 Dishes',
    },
  ];
  
  export const ratingList = [
    {
      id: 1,
      value: '1',
      label: '1🌟',
    },
    {
      id: 2,
      value: '2',
      label: '2🌟',
    },
    {
      id: 3,
      value: '3',
      label: '3🌟',
    },
    {
      id: 4,
      value: '4',
      label: '4🌟',
    },
    {
      id: 5,
      value: '5',
      label: '5🌟',
    },
  ];
  
  export const dataList = [
    {
      id: 1,
      title: 'lounge resort',
      serviceTime: '45-60min',
      deliveryFee: 3.44,
      category: 'place',
      cuisine: 'american',
      rating: 5,
      price: 2500,
      coverSrc: '/images/places/ameri.jpg',
    },
    {
      id: 2,
      title: 'door urban',
      serviceTime: '15-20min',
      deliveryFee: 4.94,
      category: 'place',
      cuisine: 'italian',
      rating: 4,
      price: 1000,
      coverSrc: '/images/places/italian.webp',
    },
    {
      id: 3,
      title: 'chow',
      serviceTime: '30-22min',
      deliveryFee: 4.94,
      category: 'place',
      cuisine: 'chinese',
      rating: 3,
      price: 2000,
      coverSrc: '/images/places/china.jpg',
    },
    {
      id: 4,
      title: 'wharf seafood',
      serviceTime: '10-18min',
      deliveryFee: 2.14,
      category: 'place',
      cuisine: 'american',
      rating: 1,
      price: 1800,
      coverSrc: '/images/places/sea.jpg',
    },
    {
      id: 5,
      title: 'Tossin',
      serviceTime: '25-30min',
      deliveryFee: 6.79,
      category: 'place',
      cuisine: 'italian',
      rating: 5,
      price: 2000,
      coverSrc: '/images/places/italiian.jpg',
    },
    {
      id: 6,
      title: 'stories noodles',
      serviceTime: '5-15min',
      deliveryFee: 2.87,
      category: 'place',
      cuisine: 'chinese',
      rating: 5,
      price: 3500,
      coverSrc: '/images/places/fookyew2.jpg',
    },
    {
      id: 7,
      title: 'Nacho cheeseburger',
      serviceTime: '50-65min',
      deliveryFee: 8.5,
      category: 'dish',
      cuisine: 'american',
      rating: 2,
      price: 2200,
      coverSrc: '/images/dishes/nacho-burger.jpg',
    },
    {
      id: 8,
      title: 'Mushroom Risotto',
      serviceTime: '10-15min',
      deliveryFee: 1.8,
      category: 'dish',
      cuisine: 'italian',
      rating: 1,
      price: 1900,
      coverSrc: '/images/dishes/Mushroom-Risotto-Recipe-1-1200.jpg',
    },
    {
      id: 9,
      title: 'Shitake Fried Rice',
      serviceTime: '12-18min',
      deliveryFee: 3.33,
      category: 'dish',
      cuisine: 'chinese',
      rating: 4,
      price: 2750,
      coverSrc: '/images/dishes/shiitake-salmon-fried-rice-0218-103230720.jpg',
    },
    {
      id: 10,
      title: 'Pesto chicken stew',
      serviceTime: '30-38min',
      deliveryFee: 1.9,
      category: 'dish',
      cuisine: 'american',
      rating: 2,
      price: 4350,
      coverSrc: '/images/dishes/pesto-chicken.jpg',
    },
    {
      id: 11,
      title: 'Bruschetta',
      serviceTime: '16-20min',
      deliveryFee: 4.1,
      category: 'dish',
      cuisine: 'italian',
      rating: 3,
      price: 3300,
      coverSrc: '/images/dishes/as-tomato-bruschetta-articleLarge.jpg',
    },
    {
      id: 12,
      title: 'Dim Sums',
      serviceTime: '24-30min',
      deliveryFee: 1.5,
      category: 'dish',
      cuisine: 'chinese',
      rating: 2,
      price: 4100,
      coverSrc: '/images/dishes/dimsums.jpg',
    },
  ];